as.constant('CONSTANTS', {
	BankId_API_KEY: '394800b7eda382955fe9b67ac958a247',
	BankId_ServiceKeyOther: '87b6b07f2f6bec3c7cdc487272a5d830',
	BankId_ServiceKeySame: 'e3d41af3c2690fcda201fcfad5991570',
	BankId_FuncName: 'FederatedLogin',
    site_Url: 'http://' + document.domain + '/',
	// Base_Url: 'http://52.59.190.252/counselor_api/api/v1.0/',
 //    Post_Image_Url: 'http://52.59.190.252/counselor_api/img/posts/thumbnails/',
	Base_Url: 'http://192.168.1.171/counselorhelp_code_deepak/counselor_api/api/v1.0/',
    Post_Image_Url: 'http://192.168.1.171/counselorhelp_code_deepak/counselor_api/img/posts/thumbnails/',
	month: '4 veckor',
    quarter: '12 veckor',
    week: '1 vecka'
});

as.constant('AccessLevels', {
    anon: 0,
    counselor: 1,
    patient:2
});

as.constant('commonPopupData', {
    "apiError": {
    	"title":"Ett fel intr&auml;ffade",
    	"para":"F&ouml;rs&ouml;k igen senare",
    	"button":"OK"
    },
    "contactUs": {
    	"title":"Tack f&ouml;r ditt meddelande!",
    	"para":"Vi har mottagit ditt meddelande och g&ouml;r v&aring;rt b&auml;sta f&ouml;r att besvara ditt meddelande s&aring; snart som m&ouml;jligt.&nbsp;",
    	"button":"OK"
    },
    "comingSoon": {
    	"title":"Tack f&ouml;r visat intresse!",
    	"para":"Vi h&aring;ller dig uppdaterad inf&ouml;r lanseringen. F&ouml;lj oss g&auml;rna p&aring; Facebook, Twitter och Instagram.&nbsp;",
    	"button":"OK"
    },
    "betaVersion": {
    	"title":"Tack f&ouml;r visat intresse!",
    	"para":"Tj&auml;nsten &auml;r just nu tillg&auml;nglig som betaversion med ett begr&auml;nsat antal anv&auml;ndare. Vi kommer att lansera v&aring;ra tj&auml;nster under h&ouml;sten 2017. F&ouml;lj oss g&auml;rna p&aring; Facebook, Twitter och Instagram f&ouml;r att h&aring;lla dig uppdaterad inf&ouml;r kommande lansering.",
    	"button":"OK"
    },
    "counselorEditProfile": {
    	"title":"Dina &auml;ndringar &auml;r under granskning",
        "para":"MinTerapi.se granskar samtliga &auml;ndringar f&ouml;r att s&auml;kerst&auml;lla att informationen du anger inte strider mot v&aring;ra anv&auml;ndarvillkor. Detta g&ouml;r vi f&ouml;r att garantera en s&auml;ker och tillf&ouml;rlitlig plattform. Dina &auml;ndringar kommer snart att synas p&aring; din profil. ",
        "button":"OK"
    },
    "checkOut": {
        "title":"Betalning genomf&ouml;rd",
    	"para":"Din betalning &auml;r nu genomf&ouml;rd.",
    	"button":"OK"
    },
    "jobApply":{
    	"para":"Tack f&ouml;r att du ans&ouml;ker om det h&auml;r jobbet.",
    	"button":"OK"
    },
    "CounselorAdminInfo":{
    	"title":"Dina &auml;ndringar &auml;r gjorda",
        "para":"Dina &auml;ndringar kommer snart att synas h&auml;r.",
        "button":"OK"
    },
    "saveBillingInfo":{
    	"title":"Informationen har sparats",
        "para":"Din faktureringsinformation har sparats. Var god l&auml;gg till ett betal- eller kreditkort f&ouml;r att forts&auml;tta.",
        "button":"OK"
    },
    "saveCard":{
    	"para":"Ditt kort sparas framg&aring;ngsrikt",
    	"button":"OK"
    },
    "saveParofileInfo":{
    	"para":"Dina uppgifter sparades framg&aring;ngsrikt",
    	"button":"OK"
    },
    "review":{
        "para":"Tack f&ouml;r din &aring;terkoppling",
        "button":"OK"
    },
    "matchingConfirmation": {
        "title":"Vill du v&auml;lja denna psykoterapeut? ",
        "para":"&Auml;r du s&auml;ker p&aring; att du vill forts&auml;tta med denna psykoterapeut? Det &auml;r inte m&ouml;jligt att byta psykoterapeut l&auml;ngre fram.",
        "success":"Ja",
        "cancel":"Nej"
    },
    "defaultCard":{
        "para":"Ditt standardkort lagras framg&aring;ngsrikt",
        "button":"OK"
    },
    "counselorsPopup": {
        "title":"Tack f&ouml;r visat intresse!",
        "para":"Vad roligt att du vill bli en del av MinTerapi.se. Vi kommer att kontakta dig inom 24 timmar med mer information. ",
        "button":"OK"
    },
    "noChangeInEditProfile":{
        "para":"Du har inte gjort n&aring;gra &auml;ndringar",
        "button":"OK"
    },
    "sessionError":{
        "para":"Din session &auml;r utg&aring;ende. V&auml;nligen f&ouml;rs&ouml;k igen senare",
        "button":"OK"
    },
    "freePlan":{
        "para":"Din fria plan &auml;r aktiv nu",
        "button":"OK"
    },
    "autoGenerated":{
        "title":"Dina &auml;ndringar sparades",
        "para":"Ditt meddelande &auml;r nu &auml;ndrat.",
        "button":"OK"
    },
    "ageVerificationError":{
        "para":"Minimi&aring;lder f&ouml;r v&aring;r tj&auml;nst &auml;r 18 &aring;r fyllda",
        "button":"OK"
    },
    "phoneSessionCheckOut":{
        "title":"Bekr&auml;ftelse p&aring; k&ouml;p",
        "para":"Detta &auml;r en bekr&auml;ftelse p&aring; ditt k&ouml;p av en telefonsession &aacute; 20 minuter&nbsp;med din psykoterapeut. Din psykoterapeut kommer att kontakta dig via terapirummet&nbsp;f&ouml;r att avtala en telefontid. Avtalad telefontid kommer d&auml;refter att visas i ditt terapirum. L&auml;s g&auml;rna mer under &ldquo;Vanliga fr&aring;gor och svar&rdquo; i huvudmenyn under fliken Hj&auml;lpcenter.",
        "button":"OK"
    },
    "deleteChatConfirmation": {
        "para":"&Auml;r du s&auml;ker p&aring; att du vill radera alla meddelande?",
        "success":"Ja",
        "cancel":"Nej"
    },
    "inactivity": {
        "title":"Automatiskt utloggad",
        "para":"Du har blivit utloggad p&aring; grund av inaktivitet. Var v&auml;nlig logga in igen om du vill forts&auml;tta.",
        "button":"OK"
    },
    "deleteChatFailure":{
        "para":"Slicka u var Hve redan tagit bort.",
        "button":"OK"
    },
    "appComingSoon":{
        "para":"Kommer finnas tillg&auml;nglig under fj&auml;rde kvartalet 2017.",
        "button":"OK"
    },
    "noFilterCounselor":{
        "para":"För tillfället finns det tyvärr inga psykoterapeuter lediga. Vänligen lämna din mailadress så återkommer vi till dig så fort vi kan.",
        "button":"Spara"
    },
    "isUserRegistrationProcess":{
        "para":"Vill du l&auml;mna den h&auml;r sidan",
        "success":"Ja",
        "cancel":"Nej"
    }
});

as.constant('commonFooterHeader', {
	footerOption: [	{name:'Om oss',path:'anon.about'},
					{name:'Terapi p&aring; n&auml;tet',path:'anon.library'},
					{name:'Vanliga fr&aring;gor',path:'anon.faq'},
					{name:'Patienter tycker',path:'anon.reviews'},
					{name:'F&ouml;r psykoterapeuter',path:'anon.counselors'}					
				],
	subFooterOption: [	{name:'F&ouml;r f&ouml;retag',path:'anon.company'},
                        {name:'Logga in (psykoterapeut)',path:'anon.login({userType:"Counselor"})'},
						{name:'Anv&auml;ndarvillkor',path:'anon.terms'}
					],
    subFooterOptionLogin: [  {name:'F&ouml;r f&ouml;retag',path:'anon.company'},
                            {name:'Anv&auml;ndarvillkor',path:'anon.terms'}
                    ],
	footerSocialLink: [	{class:'icon_twitter', path:'https://twitter.com/MinTerapi'},
						{class:'icon_linkedin', path:'https://www.linkedin.com/company-beta/17923829/'},
						{class:'icon_facebook', path:'https://www.facebook.com/minterapi.se/?fref=ts'}
					],
	loginFooter: [	{name:'Om MinTerapi.se',path:'anon'},
					{name:'Kontakta oss',path:'anon.contact'},
					{name:'Anv&auml;ndarvillkor',path:'anon.terms'}
				],
	subHeaderOption: [ 	{name:'Om oss',path:'anon.about'},
						{name:'M&ouml;t v&aring;ra psykoterapeuter',path:'anon.counselor-directory'},
						{name:'Kontakt',path:'anon.contact'},
						{name:'Media',path:'anon.media'},
						{name:'Jobb',path:'anon.jobs'},
						{name:'Advisory Board',path:'anon.advisory-board'}
				]

});

as.constant('monthName', {
	months: [
			{ id:'1', value:'Januari' },
			{ id:'2', value:'Februari' },
	        { id:'3', value:'Mars' },
	        { id:'4', value:'April' },
	        { id:'5', value:'Maj' },
	        { id:'6', value:'Juni' },
	        { id:'7', value:'Juli' },        
	        { id:'8', value:'Augusti' },
	        { id:'9', value:'September' },
	        { id:'10', value:'Oktober' },
	        { id:'11', value:'November' },
	        { id:'12', value:'December' }     
    	]
});

as.constant('cardType', {
	cards: [			
	        { id:'Visa ', value:'Visa ' },
            { id:'Mastercard', value:'Mastercard' },
            { id:'American Express', value:'American Express' }
    	]
});


as.constant('stripeError', {
    invalid_number : 'Ogiltigt kortnummer.',
    invalid_expiry_month : 'Gilighetsperioden &auml;r ogiltigt. Var god f&ouml;rs&ouml;k igen.',
    invalid_expiry_year : 'Fel giltighetsdatum (&aring;r). ',
    invalid_cvc : 'Ogiltig CVC-kod.',
    incorrect_number : 'Ogiltigt kortnummer.',
    expired_card : 'Kortet &auml;r inte l&auml;ngre giltigt.',
    incorrect_cvc : 'Ogiltig CVC-kod.',
    incorrect_zip : 'Ogiltigt postnummer.',
    processing_error : 'Ett fel uppstod vid kortk&ouml;pet.'
});